/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.morales.gui;

import com.formdev.flatlaf.FlatLightLaf; // for overall Look and Feel
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author CattoDoesCode
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        setTitle("Pisbook (Facebook clone) - Log In or Sign Up");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_female_male = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        tf_login_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pf_login_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        lbl_forgot_pass = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_signup_email = new javax.swing.JTextField();
        tf_signup_firstName = new javax.swing.JTextField();
        tf_signup_lastName = new javax.swing.JTextField();
        tf_signup_email_reEntered = new javax.swing.JTextField();
        pf_signup_pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        cb_month = new javax.swing.JComboBox<>();
        cb_day = new javax.swing.JComboBox<>();
        cb_year = new javax.swing.JComboBox<>();
        rbtn_female = new javax.swing.JRadioButton();
        rbtn_male = new javax.swing.JRadioButton();
        btn_sign_up = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(989, 542));

        jPanel1.setMinimumSize(new java.awt.Dimension(989, 542));
        jPanel1.setName(""); // NOI18N

        jPanel2.setBackground(new java.awt.Color(58, 89, 150));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pisbook");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email or Phone");

        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText("Keep me logged in");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        btn_login.setBackground(new java.awt.Color(97, 121, 170));
        btn_login.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Log In");
        btn_login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lbl_forgot_pass.setForeground(new java.awt.Color(204, 204, 204));
        lbl_forgot_pass.setText("Forgot your password?");
        lbl_forgot_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_forgot_passMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox1)
                    .addComponent(tf_login_email, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_forgot_pass))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pf_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_login)))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jCheckBox1))
                    .addComponent(jLabel1)
                    .addComponent(tf_login_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_forgot_pass))
                    .addComponent(btn_login)
                    .addComponent(pf_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(230, 233, 239));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 476));

        jPanel4.setBackground(new java.awt.Color(232, 235, 242));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Sign Up");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("It's free and always will be.");

        tf_signup_email.setForeground(java.awt.Color.gray);
        tf_signup_email.setText("Email");
        tf_signup_email.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1)));
        tf_signup_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_signup_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_signup_emailFocusLost(evt);
            }
        });

        tf_signup_firstName.setForeground(java.awt.Color.gray);
        tf_signup_firstName.setText("First Name");
        tf_signup_firstName.setToolTipText(" First Name");
        tf_signup_firstName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1)), null));
        tf_signup_firstName.setMargin(new java.awt.Insets(2, 32, 2, 6));
        tf_signup_firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_signup_firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_signup_firstNameFocusLost(evt);
            }
        });

        tf_signup_lastName.setForeground(java.awt.Color.gray);
        tf_signup_lastName.setText("Last Name");
        tf_signup_lastName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1)));
        tf_signup_lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_signup_lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_signup_lastNameFocusLost(evt);
            }
        });

        tf_signup_email_reEntered.setForeground(java.awt.Color.gray);
        tf_signup_email_reEntered.setText("Re-enter Email");
        tf_signup_email_reEntered.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1)));
        tf_signup_email_reEntered.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_signup_email_reEnteredFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_signup_email_reEnteredFocusLost(evt);
            }
        });

        pf_signup_pass.setForeground(java.awt.Color.gray);
        pf_signup_pass.setText("Password");
        pf_signup_pass.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1)));
        pf_signup_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pf_signup_passFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Brthday:");

        cb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month:", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        cb_month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_monthFocusGained(evt);
            }
        });

        cb_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cb_day.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_dayFocusGained(evt);
            }
        });

        cb_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year:", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905" }));
        cb_year.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_yearFocusGained(evt);
            }
        });

        buttonGroup_female_male.add(rbtn_female);
        rbtn_female.setText("Female");
        rbtn_female.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbtn_femaleFocusGained(evt);
            }
        });

        buttonGroup_female_male.add(rbtn_male);
        rbtn_male.setText("Male");
        rbtn_male.setToolTipText("");
        rbtn_male.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbtn_maleFocusGained(evt);
            }
        });

        btn_sign_up.setBackground(new java.awt.Color(105, 165, 77));
        btn_sign_up.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_sign_up.setForeground(new java.awt.Color(255, 255, 255));
        btn_sign_up.setText("Sign Up");
        btn_sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_upActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("Why do I need to");

        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("provide my birthday?");

        jLabel13.setText("By clicking Sign Up, you agree to our");

        jLabel14.setText("read our");

        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setText("Terms");

        jLabel16.setText("and that you have");

        jLabel17.setForeground(new java.awt.Color(102, 102, 255));
        jLabel17.setText("Data Use Policy,");

        jLabel18.setText("including our");

        jLabel19.setForeground(new java.awt.Color(102, 102, 255));
        jLabel19.setText("Cookie Use.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(tf_signup_email)
                        .addComponent(tf_signup_email_reEntered)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(tf_signup_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_signup_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pf_signup_pass))
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cb_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbtn_female)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn_male))
                    .addComponent(btn_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addGap(0, 76, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_sign_up, tf_signup_firstName, tf_signup_lastName});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_signup_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_signup_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_signup_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_signup_email_reEntered, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_signup_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_year, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addComponent(cb_day)
                    .addComponent(cb_month)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_female)
                    .addComponent(rbtn_male))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(btn_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tf_signup_firstName, tf_signup_lastName});

        jPanel5.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(58, 89, 150));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pisbook helps you connect and share with");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 89, 150));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("the people in your life.");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/morales/gui/assets/world_connect.png"))); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void lbl_forgot_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgot_passMouseClicked
        JOptionPane.showMessageDialog(this, "sad :(", "Message", -1 );
    }//GEN-LAST:event_lbl_forgot_passMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        UserAuthentication user_auth = new UserAuthentication();
        
        String u_name = tf_login_email.getText();
        String u_pass = new String (pf_login_pass.getPassword());
        
        boolean login_success = user_auth.log_in(u_name, u_pass);
        
        if (login_success == true) {
            JOptionPane.showMessageDialog(this, "log in successful");
        }
        else {
            JOptionPane.showMessageDialog(this, "invalid email or password!");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign_upActionPerformed

        
        String firstName = tf_signup_firstName.getText();
        String lastName = tf_signup_lastName.getText();
        String emailAdd = tf_signup_email.getText();
        String reEmailAdd = tf_signup_email_reEntered.getText();
        String pass = new String(pf_signup_pass.getPassword());
        String month = "" + cb_month.getSelectedItem(); // empty String concatenation changes the return Object to String 
        String day = "" + cb_day.getSelectedItem();
        String year = "" + cb_year.getSelectedItem();
        String sex;
        if (rbtn_female.isSelected()) {
            sex = "female";
        }
        else if (rbtn_male.isSelected()){
            sex = "male";
        }
        else {
            sex = "";
        }
        
        
        // TODO: error catcher - re-enter email, weak password, invalid email
        if (firstName.equals("First Name") || lastName.equals("Last Name") || emailAdd.equals("Email") || reEmailAdd.equals("Re-enter Email") || pass.equals("Password") || month.equals("Month:") || day.equals("Day:") || year.equals("Year:") || sex.isEmpty()) {
            if (firstName.equals("First Name")) {
                tf_signup_firstName.setForeground(Color.red);
            }
            if (lastName.equals("Last Name")) {
                tf_signup_lastName.setForeground(Color.red);
            }
            if (emailAdd.equals("Email")) {
                tf_signup_email.setForeground(Color.red);
            }
            if (reEmailAdd.equals("Re-enter Email")) {
                tf_signup_email_reEntered.setForeground(Color.red);
            }
            if (pass.equals("Password")) {
                pf_signup_pass.setForeground(Color.red);
            }
            if (month.equals("Month:")) {
                cb_month.setForeground(Color.red);
            }
            if (day.equals("Day:")) {
                cb_day.setForeground(Color.red);
            }
            if (year.equals("Year:")) {
                cb_year.setForeground(Color.red);
            }
            if (sex.isEmpty()) {
                rbtn_female.setForeground(Color.red);
                rbtn_male.setForeground(Color.red);
            }
            
            JOptionPane.showMessageDialog(this, "please fill in required fields!");
        }
        else {
            UserAuthentication user_auth = new UserAuthentication();
            user_auth.sign_up(firstName, lastName, emailAdd, reEmailAdd, pass, month, day, year, sex);
            JOptionPane.showMessageDialog(this, "Sign Up successful!");
        }
        
    }//GEN-LAST:event_btn_sign_upActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Sign Up Fields Focus Listeners">    
    private void tf_signup_lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_lastNameFocusGained
        if (tf_signup_lastName.getText().equals("Last Name")) {
            tf_signup_lastName.setText("");
            tf_signup_lastName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_signup_lastNameFocusGained

    private void tf_signup_lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_lastNameFocusLost
        if (tf_signup_lastName.getText().isEmpty()) {
            tf_signup_lastName.setForeground(Color.GRAY);
            tf_signup_lastName.setText("Last Name");
        }
    }//GEN-LAST:event_tf_signup_lastNameFocusLost

    private void tf_signup_firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_firstNameFocusGained
        if (tf_signup_firstName.getText().equals("First Name")) {
            tf_signup_firstName.setText("");
            tf_signup_firstName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_signup_firstNameFocusGained

    private void tf_signup_firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_firstNameFocusLost
        if (tf_signup_firstName.getText().isEmpty()) { 
            tf_signup_firstName.setForeground(Color.GRAY);
            tf_signup_firstName.setText("First Name");
        }
    }//GEN-LAST:event_tf_signup_firstNameFocusLost

    private void tf_signup_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_emailFocusGained
        if (tf_signup_email.getText().equals("Email")) {
            tf_signup_email.setText("");
            tf_signup_email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_signup_emailFocusGained

    private void tf_signup_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_emailFocusLost
        if (tf_signup_email.getText().isEmpty()) { 
            tf_signup_email.setForeground(Color.GRAY);
            tf_signup_email.setText("Email");
        }
    }//GEN-LAST:event_tf_signup_emailFocusLost

    private void tf_signup_email_reEnteredFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_email_reEnteredFocusGained
        if (tf_signup_email_reEntered.getText().equals("Re-enter Email")) {
            tf_signup_email_reEntered.setText("");
            tf_signup_email_reEntered.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_signup_email_reEnteredFocusGained

    private void tf_signup_email_reEnteredFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_signup_email_reEnteredFocusLost
        if (tf_signup_email_reEntered.getText().isEmpty()) { 
            tf_signup_email_reEntered.setForeground(Color.GRAY);
            tf_signup_email_reEntered.setText("Re-enter Email");
        }
    }//GEN-LAST:event_tf_signup_email_reEnteredFocusLost

    private void pf_signup_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_signup_passFocusGained
        pf_signup_pass.setText("");
        pf_signup_pass.setForeground(Color.BLACK);
    }//GEN-LAST:event_pf_signup_passFocusGained

    private void cb_monthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_monthFocusGained
        cb_month.setForeground(Color.BLACK);
    }//GEN-LAST:event_cb_monthFocusGained

    private void cb_dayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_dayFocusGained
        cb_day.setForeground(Color.BLACK);
    }//GEN-LAST:event_cb_dayFocusGained

    private void cb_yearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_yearFocusGained
        cb_year.setForeground(Color.BLACK);
    }//GEN-LAST:event_cb_yearFocusGained

    private void rbtn_femaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbtn_femaleFocusGained
        rbtn_female.setForeground(Color.BLACK);
        rbtn_male.setForeground(Color.BLACK);
    }//GEN-LAST:event_rbtn_femaleFocusGained

    private void rbtn_maleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbtn_maleFocusGained
        rbtn_male.setForeground(Color.BLACK);
        rbtn_female.setForeground(Color.BLACK);
    }//GEN-LAST:event_rbtn_maleFocusGained
    // </editor-fold> 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LandingPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_sign_up;
    private javax.swing.ButtonGroup buttonGroup_female_male;
    private javax.swing.JComboBox<String> cb_day;
    private javax.swing.JComboBox<String> cb_month;
    private javax.swing.JComboBox<String> cb_year;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_forgot_pass;
    private javax.swing.JPasswordField pf_login_pass;
    private javax.swing.JPasswordField pf_signup_pass;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTextField tf_login_email;
    private javax.swing.JTextField tf_signup_email;
    private javax.swing.JTextField tf_signup_email_reEntered;
    private javax.swing.JTextField tf_signup_firstName;
    private javax.swing.JTextField tf_signup_lastName;
    // End of variables declaration//GEN-END:variables
}
